name: lawyer_consultant_for_lawyers
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0

environment:
 sdk: '>=3.1.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  resize: ^1.0.0
  carousel_slider: ^4.2.1
  get_storage: ^2.1.1
  skeleton_loader: ^2.0.0+4
  modal_progress_hud_nsn: ^0.3.0
  shared_preferences: ^2.1.0
  bottom_navy_bar: ^6.1.0
  dio: ^5.1.1
  global_configuration: ^2.0.0-nullsafety.1
  intl: ^0.18.0
  agora_rtc_engine: ^5.2.0
  permission_handler: ^10.4.3
  flutter_local_notifications: ^9.0.2
  firebase_messaging: ^14.4.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.1.2
  weekday_selector: ^1.1.0
  image_picker_gallery_camera: ^0.2.2
  crypto: ^3.0.0
  pusher_channels_flutter: ^2.2.0
  pusher_beams: ^1.1.1
  wakelock: ^0.6.1+2
  flutter_facebook_auth: ^5.0.11
  google_sign_in: ^5.4.1
  flutter_html: ^3.0.0-alpha.6
  file_picker: ^5.0.0
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/cfg/
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages